name: eraser_example
description: Demonstrates how to use the eraser plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eraser:
    path: ../
  move_to_background: ^1.0.1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  http: ^0.12.2
  googleapis_auth: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - privatekey/