name: eraser_example
description: Demonstrates how to use the eraser plugin.

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  eraser:
    path: ../
  move_to_background: ^1.0.2
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  http: ^1.2.2
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - privatekey/